### PR TITLE
Fix REPO-4317 ambitious body

### PR DESCRIPTION
**Pull request by mmuller88**
* Use array as schema definition where we allow using arrays.

### CODE REVIEW

**Comment by killerboot** [comment]
I suspect this is not a backwards compatible change. Will the customers have to rewrite their apps?

**Comment by killerboot** [comment]
What about the underlying code in repository? Does it have to change as well?

**Comment by killerboot** [comment]
I added @jamalkm as a reviewer. Please check if the changes are acceptable from the "builder" project 
perspective

**Comment by mmuller88** [comment]
Makes perfect thanks. I will close the PR. Many thanks for the valuable feedback guys.

**Pull request closed without merging**
