### PR TITLE
REPO-2557, ALF-21907. Lock owner can create, edit, delete comments.

### PR DESCRIPTION
**Pull request by mmuller88**

### CODE REVIEW

**Comment by mmuller88** [comment]
I'm not sure maybe I should had check out from master? I checked out from 5.2.N because there was no develop branch. Normally we should use a develop branch or not? I guess you using master instead of develop.

**Comment by Epurashu** [comment]
I think it is a good practice to use 5.2.N instead of master.

**Comment by gavincornwell** [comment]
Correct, the branch structure of this project deliberately matches that of the platform SVN branch structure so they keep aligned.

As for the changes, they look fine to me, go ahead and merge.

**Comment by montgolfiere** [comment]
Once the repo code moves to git there will also be a develop (likely for 5.3+) so we can do the same here at that time. In the meantime, please use 5.2.N as per Gav's comment above.

**Pull request merged**
